# Generated by Django 5.2.7 on 2025-11-03 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent feature for marking this as a variation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variations",
                to="main.feature",
            ),
        ),
    ]
